dist: trusty

sudo: required

language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - '7'

php:
  - '7.0'

services:
  - mysql

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser
#  - sudo apt-get install php7.0 php7.0-fpm php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y

before_script:
  - npm prune
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script: 
  - npm run test
  - sh coverage-checker.sh
  - php -r 'echo "Php works\n";'

after_success:
   - npm run coverage
   
# notifications:
#   slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
#   email: false
