dist: trusty

sudo: required

language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - '7'

php:
  - '7.0'

services:
  - mysql

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser
#  - sudo apt-get install php7.0 php7.0-fpm php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y

before_script:
  # install Apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - git clone --depth=50 --branch=master https://github.com/Toolwatchapp/tw-backend.git tw-backend
  - sudo cp -f tests/e2e/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # node configuration
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - npm run test
  - sh coverage-checker.sh
  - php -r 'echo "Php works\n";'

after_success:
   - npm run coverage
   
# notifications:
#   slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
#   email: false
