language: node_js

cache: yarn

sudo: false

notifications:
  email: false

node_js:
  - '7'

php:
  - '7.0'

services:
  - mysql

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - npm prune

script: 
  - npm run test
  - sh coverage-checker.sh

after_success:
   - npm run coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# notifications:
#   slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
#   email: false