sudo: required

language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - '7'

php:
  - '7.0'

services:
  - mysql

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser
  - sudo apt-get install php7.0 php7.0-fpm php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y

before_script:
  - npm prune

script: 
  - npm run test
  - sh coverage-checker.sh
  - php -r 'echo "Php works\n";'

after_success:
   - npm run coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# notifications:
#   slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
#   email: false
